feat: add `biome.configPath` option
biomejs/biome-vscode pull request #33
Opened 2023-12-09 14:05 UTC by nhedger

fixes #28

2023-12-09 14:34 UTC, nhedger commented
I mistakenly thought that the __print_socket command already accepted a `--config-path` argument but this is not the case. Going forward with this PR is going to require modifying the CLI to allow this arg.

2023-12-09 15:07 UTC, ematipico commented
I completely forgot that the VSCode extension bootstraps the daemon in a different way. I think we can add it easily to the LSP.

2023-12-10 11:58 UTC, nhedger commented
Yep, I'll take care of it.

2024-01-29 15:30 UTC, Malix-off requested changes
Comply with #101

2024-01-29 15:30 UTC, Malix-off commented on package.json
> +					"default": null,
```suggestion
					"type": "string",
					"default": "",
```

2024-01-29 15:30 UTC, Malix-off commented on src/main.ts
> +		.get<string | null>("biome.configPath");
```suggestion
		.get<string>("biome.configPath");
```

2024-01-29 15:30 UTC, Malix-off commented on src/main.ts
> +	if (configPath && configPath.length > 0) {
```suggestion
	if (configPath) {
```

## Rationale

```js
Boolean("") // false
Boolean(" ") // true
```

2024-02-10 23:14 UTC, closed without merging

2024-02-11 00:07 UTC, Malix-off commented
@nhedger can you provide reasons as of why this PR has been closed?

2024-02-11 09:36 UTC, nhedger commented
We'll be going a different way that doesn't involve passing the setting as an arg.

2025-03-28 18:31 UTC, skipjack commented
@nhedger is there a way to do this now? I don't see that alternative linked here or in the close issue relating to it.

2025-03-28 18:33 UTC, skipjack commented
Disregard, I see [your comment here][1] now... trying that out.

[1]: https://github.com/biomejs/biome-vscode/issues/28#issuecomment-2358605741